name: instagroot
description: Instagram clone for Groot created using Flutter!

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  outline_material_icons: ^0.1.0
  timeago: ^2.0.14
  carousel_slider: ^1.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  image_path: "assets/images/launcher_groot.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Billabong
    fonts:
    - asset: assets/fonts/Billabong.ttf